receivers:
  jaeger:
    protocols:
      grpc:

exporters:
  otlp/2:
    endpoint: situp:21890
    ca_file: /etc/demo-situp.crt
  logging:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, otlp/2]
